### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by nassimabedi** [mushorg/go-dpi#52]
I have this error many times.

> Number of packets: 1336
Number of packets identified: 1053
Protocols identified:
 map[DNS:6 SSL:1047]
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers.(*DNSQuestion).decode(0xc422134ab8, 0xc4213981ea, 0x10, 0x10, 0xc, 0xb75dc0, 0xc4215c8de0, 0xc422134c08, 0xc422134a90, 0x64e1f6e1, ...)
	/root/go/src/github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers/dns.go:617 +0x1af
github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers.(*DNS).DecodeFromBytes(0xc421189b60, 0xc4213981ea, 0x10, 0x10, 0xb75dc0, 0xc4215c8de0, 0xc42002f880, 0x7f681d2bd000)
	/root/go/src/github.com/mushorg/go-dpi/vendor/github.com/google/gopacket/layers/dns.go:328 +0x292
github.com/mushorg/go-dpi/modules/classifiers.DNSClassifier.HeuristicClassify.func1(0xb7ab00, 0xc4211d9700, 0xb7ab00)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/dns.go:17 +0xa5
github.com/mushorg/go-dpi/modules/classifiers.checkFlowLayer(0xc421164410, 0x2d, 0x7a0ae8, 0x41908d)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/classifiers.go:110 +0xa5
github.com/mushorg/go-dpi/modules/classifiers.DNSClassifier.HeuristicClassify(0xc421164410, 0x7f681d230598)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/dns.go:14 +0x43
github.com/mushorg/go-dpi/modules/classifiers.(*DNSClassifier).HeuristicClassify(0x10f1238, 0xc421164410, 0x10f1238)
	<autogenerated>:1 +0x3e
github.com/mushorg/go-dpi/modules/classifiers.(*ClassifierModule).ClassifyFlow(0xc42112aa80, 0xc421164410, 0xc422134af8, 0xc422134d80, 0x696115, 0xb7f140)
	/root/go/src/github.com/mushorg/go-dpi/modules/classifiers/classifiers.go:78 +0xb2
github.com/mushorg/go-dpi.ClassifyFlow(0xc421164410, 0xc421173680, 0xc421164410, 0x1, 0x1)
	/root/go/src/github.com/mushorg/go-dpi/godpi.go:94 +0x79
main.main()
	/root/go/src/github.com/mushorg/go-dpi/godpi_example/example_app.go:75 +0x524

and sometimes I got this error.

> Get https://raw.githubusercontent.com/wiki/mushorg/go-dpi/2grams_tcp.model: dial tcp: lookup raw.githubusercontent.com on 192.168.1.1:53: read udp 192.168.1.2:35056->192.168.1.1:53: i/o timeout
Get https://raw.githubusercontent.com/wiki/mushorg/go-dpi/2grams_tcp.model: dial tcp: lookup raw.githubusercontent.com on 192.168.1.1:53: read udp 192.168.1.2:37833->192.168.1.1:53: i/o timeout

**Comment by nikofil** [comment]
Your first issue shouldn't happen anymore, as of my last commit. Can you make sure you have the last version, and run `glide update` to fetch the latest `gopacket` version too (as that's where the issue is)?
As for your second issue, that must be either your internet or the github server timing out, so it's not really an issue with the library. What you can do, however, to avoid it in the future, is download the 2 files (https://raw.githubusercontent.com/wiki/mushorg/go-dpi/2grams_tcp.model and https://raw.githubusercontent.com/wiki/mushorg/go-dpi/2grams_udp.model) and save them somewhere, then change the file `linearsvc.go` at lines 195 and 196 and provide the local path to the files instead of the URL, so they're not downloaded every time.
